site_name: EPIC-api documentation
# theme: readthedocs
theme:
  name: material
  language: en
  icon:
    logo: material/leaf
  palette:
    - scheme: deltares
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            show_source: true
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: false
          selection:
            inherited_members: false

      custom_templates: templates
      watch:
        - src/core
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
repo_url: https://github.com/Deltares/EPIC-api
repo_name: deltares/epic-api
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Deltares/EPIC-api
      name: Source code
copyright: Copyright &copy; 2022 Deltares
extra_css:
  - stylesheets/extra.css