# Generated by Django 4.0.5 on 2022-07-04 13:14

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Agencies",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="EpicOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="epic_app.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField()),
                ("reference_description", models.TextField(blank=True, null=True)),
                ("reference_link", models.URLField(blank=True)),
                (
                    "agencies",
                    models.ManyToManyField(
                        blank=True, related_name="programs", to="epic_app.agency"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="epic_app.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="epic_app.program",
                    ),
                ),
            ],
            options={
                "unique_together": {("title", "program")},
            },
        ),
        migrations.CreateModel(
            name="AgreementAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="epic_app.answer",
                    ),
                ),
                (
                    "selected_choice",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name=[
                            ("STRONGLYDISAGREE", "Strongly disagree"),
                            ("DISAGREE", "Disagree"),
                            ("NEITHERAGREENORDISAGREE", "Neither agree nor disagree"),
                            ("AGREE", "Agree"),
                            ("STRONGLYAGREE", "Strongly agree"),
                        ],
                    ),
                ),
                ("justify_answer", models.TextField(blank=True)),
            ],
            bases=("epic_app.answer",),
        ),
        migrations.CreateModel(
            name="EvolutionAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="epic_app.answer",
                    ),
                ),
                (
                    "selected_choice",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name=[
                            ("NASCENT", "Nascent"),
                            ("ENGAGED", "Engaged"),
                            ("CAPABLE", "Capable"),
                            ("EFFECTIVE", "Effective"),
                        ],
                    ),
                ),
                ("justify_answer", models.TextField(blank=True)),
            ],
            bases=("epic_app.answer",),
        ),
        migrations.CreateModel(
            name="EvolutionQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="epic_app.question",
                    ),
                ),
                (
                    "nascent_description",
                    models.TextField(blank=True, null=True, verbose_name="NASCENT"),
                ),
                (
                    "engaged_description",
                    models.TextField(blank=True, null=True, verbose_name="ENGAGED"),
                ),
                (
                    "capable_description",
                    models.TextField(blank=True, null=True, verbose_name="CAPABLE"),
                ),
                (
                    "effective_description",
                    models.TextField(blank=True, null=True, verbose_name="EFFECTIVE"),
                ),
            ],
            bases=("epic_app.question",),
        ),
        migrations.CreateModel(
            name="KeyAgencyActionsQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="epic_app.question",
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("epic_app.question",),
        ),
        migrations.CreateModel(
            name="LinkagesQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="epic_app.question",
                    ),
                ),
            ],
            bases=("epic_app.question",),
        ),
        migrations.CreateModel(
            name="NationalFrameworkQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="epic_app.question",
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("epic_app.question",),
        ),
        migrations.CreateModel(
            name="EpicUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_advisor", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users",
                        to="epic_app.epicorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_answers",
                to="epic_app.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="epic_app.epicuser",
            ),
        ),
        migrations.CreateModel(
            name="MultipleChoiceAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="epic_app.answer",
                    ),
                ),
                (
                    "selected_programs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="selected_answers",
                        to="epic_app.program",
                    ),
                ),
            ],
            bases=("epic_app.answer",),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("user", "question")},
        ),
    ]
