# Generated by Django 4.0.5 on 2022-09-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epic_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="reference_description",
        ),
        migrations.RemoveField(
            model_name="program",
            name="reference_link",
        ),
        migrations.CreateModel(
            name="ProgramReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="epic_app.program",
                    ),
                ),
            ],
        ),
    ]
